### ISSUE TITLE
Need a Nuget package for .NET Core / .NET 5

### ISSUE THREAD

**Issue by hempels** [prowriting/prowritingaid.csharp#1]
Imperative: .NET Framework 4.5 is the end of the road for that line. Beginning .NET 5, everything is built off the .NET Core code base. So at the very least, a new NuGet package built for .NET 5 is needed.

Making the package compatible with .NET Core 3.1 should cover both .NET Core 3 and .NET 5.

**Comment by prowriting** [comment]
Hi! Yep, we just merged a PR, SDK packages are targeting .net standard 2.0.
